name: EffectUI
api: 4.0.0
main: FRashkar\EffectUI\Main
version: 1.0.0
author: FRashkar-pm
description: EffectUI

commands:
  effectui:
    description: Open EffectUI
    permission: effectui.cmd
    
permissions:
  effectui.cmd:
    description: Allow you to use effectui!
    default: op
